X = input("Give first of the your three numbers: ")
Y = input("Give second of your three numbers")
Z = input("Give the last number")
if X > Y and X > Z:  print("X = " +str(X))
elif X >Y and Y > Z: print("Y = " +str(Y))
else: print("Z = " +str(Z))
